sudo : required
language: generic 
services:
 - docker
before_install:
 - docker build -t imrabhinav/docker-react -f Dockerfile.dev .


script:
 #- docker run imrabhinav/docker-react npm run test -- --coverage
 - docker run -e CI=true ashish-abhinav/docker-react npm run test